# Generated by Django 5.2.3 on 2025-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3)),
                ('category', models.CharField(choices=[('Food', 'Еда'), ('Transport', 'Транспорт'), ('Entertainments', 'Развлечения'), ('Utilities', 'Коммунальные услуги'), ('Other', 'Другое')], default='Other', max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
